/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ui.legacy.exportXML.ui;

import csheets.ui.ctrl.UIController;
import csheets.ui.legacy.exportXML.ExportXMLController;
import javax.swing.JFileChooser;

/**
 *
 * @author ruben
 */
public class ExportXMLPanel extends javax.swing.JFrame {

	private final ExportXMLController controller;
	private UIController uiController;

	/**
	 * Creates new form ExportXMLPanel
	 *
	 * @param uiController uiController
	 */
	public ExportXMLPanel(UIController uiController) {
		initComponents();
		this.uiController = uiController;
		this.controller = new ExportXMLController(this.uiController);
		initiateOptions();
		this.jComboBoxSpreedSheet.setEnabled(false);
	}

	/**
	 * Method to add Items
	 */
	private void initiateOptions() {
		this.jComboBoxType.removeAll();
		this.jComboBoxType.addItem("Workbook");
		this.jComboBoxType.addItem("SpreedSheet");
		this.jComboBoxType.addItem("SpreedSheet Selected");
		this.jComboBoxSpreedSheet.removeAll();
		for (int i = 0; i < this.uiController.getActiveWorkbook().
			getSpreadsheetCount(); i++) {
			this.jComboBoxSpreedSheet.addItem(this.uiController.
				getActiveWorkbook().getSpreadsheet(i).getTitle());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        jButtonExport = new javax.swing.JButton();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSpreedSheet = new javax.swing.JComboBox<>();
        jToggleButtonCancel = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTagColumn = new javax.swing.JTextField();
        jTextFieldTagWorkbook = new javax.swing.JTextField();
        jTextFieldTagSpreadSheet = new javax.swing.JTextField();
        jTextFieldTagRow = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CellFontTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CommentTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BackgroundTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BorderTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ValueTextField = new javax.swing.JTextField();

        checkbox1.setLabel("export selected");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonExport.setText("Export");
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jLabel2.setText("SpreedSheet:");

        jToggleButtonCancel.setText("Cancel");
        jToggleButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("WoorkBook:");

        jLabel4.setText("SpreadSheet:");

        jLabel5.setText("Row:");

        jLabel6.setText("Column:");

        jTextFieldTagColumn.setText("Column");

        jTextFieldTagWorkbook.setText("WorkBook");
        jTextFieldTagWorkbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTagWorkbookActionPerformed(evt);
            }
        });

        jTextFieldTagSpreadSheet.setText("SpreadSheet");
        jTextFieldTagSpreadSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTagSpreadSheetActionPerformed(evt);
            }
        });

        jTextFieldTagRow.setText("Row");

        jLabel7.setText("Tags");

        jLabel8.setText("Font");

        CellFontTextField.setText("Font");
        CellFontTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellFontTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Comment");

        CommentTextField.setText("Comment");
        CommentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Background");

        BackgroundTextField.setText("Background");
        BackgroundTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackgroundTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Border");

        BorderTextField.setText("Border");

        jLabel12.setText("Value");

        ValueTextField.setText("Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel7)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonExport)
                        .addGap(27, 27, 27)
                        .addComponent(jToggleButtonCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSpreedSheet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTagWorkbook))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addComponent(jTextFieldTagSpreadSheet))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTagRow)
                                    .addComponent(jTextFieldTagColumn)
                                    .addComponent(ValueTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(CellFontTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackgroundTextField)
                                    .addComponent(BorderTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)
                                .addComponent(CommentTextField)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSpreedSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTagWorkbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTagSpreadSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTagRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTagColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CellFontTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(BackgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(BorderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(CommentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonCancel)
                    .addComponent(jButtonExport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
		JFileChooser fileChooser = new JFileChooser();
		int retrival = fileChooser.showSaveDialog(null);
		if (retrival == JFileChooser.APPROVE_OPTION) {
			try {

				switch (this.jComboBoxType.getSelectedIndex()) {
					case 0:
						this.controller.
							exportWorkbook(fileChooser, this.jTextFieldTagWorkbook.
										   getText(), this.jTextFieldTagSpreadSheet.
										   getText(), this.jTextFieldTagRow.
										   getText(), this.jTextFieldTagColumn.
										   getText(), this.ValueTextField.
										   getText(), this.CellFontTextField.
										   getText(), this.BackgroundTextField.
										   getText(), this.BorderTextField.
										   getText(), this.CommentTextField.
										   getText());
						break;
					case 1:
						this.controller.
							exportSpreadSheet(fileChooser, this.jTextFieldTagSpreadSheet.
											  getText(), this.jTextFieldTagRow.
											  getText(), this.jTextFieldTagColumn.
											  getText(), this.ValueTextField.
											  getText(), this.CellFontTextField.
											  getText(), this.BackgroundTextField.
											  getText(), this.BorderTextField.
											  getText(), this.CommentTextField.
											  getText(), this.uiController.
											  getActiveWorkbook().
											  getSpreadsheet(this.jComboBoxSpreedSheet.
												  getSelectedIndex()));
						break;
					default:
						this.controller.
							exportSpreadSheetSelected(fileChooser, this.jTextFieldTagSpreadSheet.
													  getText(), this.jTextFieldTagRow.
													  getText(), this.jTextFieldTagColumn.
													  getText());
						break;
				}
				this.dispose();
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}
    }//GEN-LAST:event_jButtonExportActionPerformed

    private void jToggleButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelActionPerformed
		this.dispose();
    }//GEN-LAST:event_jToggleButtonCancelActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
		if (this.jComboBoxType.getSelectedIndex() == 1) {
			this.jComboBoxSpreedSheet.setEnabled(true);
		} else {
			this.jComboBoxSpreedSheet.setEnabled(false);
		}
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jTextFieldTagSpreadSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTagSpreadSheetActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTagSpreadSheetActionPerformed

    private void CellFontTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellFontTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_CellFontTextFieldActionPerformed

    private void jTextFieldTagWorkbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTagWorkbookActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTagWorkbookActionPerformed

    private void CommentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_CommentTextFieldActionPerformed

    private void BackgroundTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackgroundTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_BackgroundTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BackgroundTextField;
    private javax.swing.JTextField BorderTextField;
    private javax.swing.JTextField CellFontTextField;
    private javax.swing.JTextField CommentTextField;
    private javax.swing.JTextField ValueTextField;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JComboBox<String> jComboBoxSpreedSheet;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldTagColumn;
    private javax.swing.JTextField jTextFieldTagRow;
    private javax.swing.JTextField jTextFieldTagSpreadSheet;
    private javax.swing.JTextField jTextFieldTagWorkbook;
    private javax.swing.JToggleButton jToggleButtonCancel;
    // End of variables declaration//GEN-END:variables

}
