/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ui.FormEditor.ui;

import csheets.core.Cell;
import csheets.notification.Notification;
import csheets.ui.ctrl.FormEditorController;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;

/**
 *
 * @author hichampt
 */
public class FormEditorUpdate extends javax.swing.JFrame implements Observer {

	/**
	 * Creates new form FormEditor
	 */
	FormEditorController controller;

	public FormEditorUpdate(Cell cell) {
		this.controller = new FormEditorController(cell);
		Notification.formInformer().addObserver(this);
		super.setAlwaysOnTop(true);
		initComponents();
		setVisible(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setLayout(new java.awt.GridLayout(5, 1, 5, 5));
        jScrollPane1.setViewportView(mainPanel);

        addButton.setText("Add");

        cancelButton.setText("Cancel");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(19, 19, 19))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton)
                    .addComponent(updateButton))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(465, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
		// TODO add your handling code here:

    }//GEN-LAST:event_updateButtonActionPerformed

	/**
	 * Add new Line
	 *
	 * @param panel
	 */
	private void addPanel(JPanel panel) {
		this.mainPanel.add(panel);
		addGridRow();
	}

	/**
	 * Remove line
	 *
	 * @param panel
	 */
	private void removePanel(JPanel panel) {
		this.mainPanel.remove(panel);
		removeGridRow();
	}

	/**
	 * Layout specific: set's the default number of rows (5).
	 */
	private void defaultGridRow() {
		((GridLayout) this.mainPanel.getLayout()).setRows(5);
	}

	/**
	 * Layout specific: add's a row to the panel's layout (to prevent adding a
	 * new column).
	 */
	private void addGridRow() {
		GridLayout layout = (GridLayout) this.mainPanel.getLayout();
		layout.setRows(layout.getRows() + 1);
	}

	/**
	 * Remove row grid.
	 */
	private void removeGridRow() {
		GridLayout layout = (GridLayout) this.mainPanel.getLayout();
		layout.setRows(layout.getRows() - 1);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

	private void refreshUI() {
		mainPanel.revalidate();
		mainPanel.repaint();
	}

	@Override
	public void update(Observable o, Object o1) {
		if (o1 instanceof JPanel) {
			removePanel((JPanel) o1);
			refreshUI();
		}
	}

}
