/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.contacts.ui;

import csheets.domain.Contact;
import csheets.ext.contacts.ContactsExtension;
import csheets.ui.ctrl.UIController;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author Rui Freitas <1130303>
 */
public class ContactsPanel extends JPanel {

    private ContactsController theController = new ContactsController();

    /**
     * Creates new form ContactsPanel
     */
    public ContactsPanel(UIController controller) {
        setName(ContactsExtension.NAME);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(100, 50));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(new java.awt.Dimension(100, 50));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setLayout(new java.awt.BorderLayout());

        addBtn.setText("+");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, java.awt.BorderLayout.WEST);

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel1.add(editBtn, java.awt.BorderLayout.CENTER);

        removeBtn.setText("-");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(removeBtn, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contactsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contactsPanel.setLayout(new java.awt.GridLayout(5, 1));
        jScrollPane2.setViewportView(contactsPanel);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        new AddContactDialog(null, theController).setVisible(true);
        refreshContactCards();
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if (this.contactsPanel.getComponentCount() == 0) {
            refreshContactCards();
        }
    }//GEN-LAST:event_formComponentShown

    private void clearContactList() {
        this.contactsPanel.removeAll();
        defaultGridRow();
        refreshUI();
    }

    private void refreshContactCards() {
        ContactCardPanel card;
        clearContactList();

        for (Contact ct : this.theController.allContacts()) {
            card = new ContactCardPanel();
            card.setFirstName(ct.firstName());
            card.setLastName(ct.lastName());
            try {
                card.setPhoto(this.theController.contactPhoto(ct));
            } catch (IOException ex) {
                System.out.println("erro");
            }
            addContactCard(card);
        }
        refreshUI();
    }

    private void addContactCard(JComponent comp) {
        this.contactsPanel.add(comp);
        addGridRow();

    }

    private void defaultGridRow() {
        ((GridLayout) this.contactsPanel.getLayout()).setRows(5);
    }

    private void addGridRow() {
        GridLayout layout = (GridLayout) this.contactsPanel.getLayout();

        layout.setRows(layout.getRows() + 1);

    }

    private void refreshUI() {
        contactsPanel.revalidate();
        contactsPanel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel contactsPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
