/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.game.ui;

import csheets.ext.game.Battleships;
import csheets.ext.game.GameExtension;
import csheets.ext.game.TicTacToe;
import csheets.support.Task;
import csheets.support.TaskManager;
import csheets.ui.DefaulListModel;
import csheets.ui.ctrl.SelectionEvent;
import csheets.ui.ctrl.SelectionListener;
import csheets.ui.ctrl.UIController;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author João Martins
 */
public class GamePanel extends javax.swing.JPanel implements SelectionListener, Observer {

	/**
	 * Tic-tac-toe designation.
	 */
	private static final String TIC_TAC_TOE = "Tic-Tac-Toe";

	/**
	 * Battleships designation.
	 */
	private static final String BATTLESHIPS = "Battleships";

	private String username;

	/**
	 * Profile photo.
	 */
	private File photoFile;

	/**
	 * UI controller.
	 */
	private final UIController uiController;

	/**
	 * Instance of the controller.
	 */
	private GameController gameController;

	/**
	 * Default instance list - instances.
	 */
	private DefaultListModel instanceListModel;

	/**
	 * Default instance list - list of games.
	 */
	private DefaultListModel instanceListModelGames;

	/**
	 * Default instance list - list online games.
	 */
	private DefaultListModel instanceListModelOnlineGames;

	/**
	 * Opponent.
	 */
	private String opp;

	/**
	 * Task Manager.
	 */
	private final TaskManager manager = new TaskManager();

	/**
	 * Creates new form GamePanel.
	 *
	 * @param uiController uiController
	 * @param gameController gameController
	 * @throws java.net.UnknownHostException exception
	 */
	public GamePanel(UIController uiController, GameController gameController) {
		this.uiController = uiController;

		setName(GameExtension.NAME);

		// Create default lists
		instanceListModel = new DefaultListModel();
		instanceListModelGames = new DefaulListModel();
		instanceListModelOnlineGames = new DefaulListModel();
		initComponents();

		uiController.addSelectionListener(this);

		opponentsList.setModel(instanceListModel);
		gameList.setModel(instanceListModelGames);
		gamingOpponents.setModel(instanceListModelOnlineGames);

		updateListOfGames();
		updateSystemProperty();

		try {
			updateLocalHostName();
		} catch (UnknownHostException ex) {
			Logger.getLogger(GamePanel.class.getName()).
				log(Level.SEVERE, null, ex);
		}

		// @IMPROVEMENT: Needs to get the timer from the configuration.
		// Maybe get it through a configuration file?
		final int defaultSeconds = 10;
		final int defaultPort = 20006;

		this.gameController = gameController;
		this.gameController.startUdpService(this, defaultPort, defaultSeconds);
		this.gameController.startTcpService(this, defaultPort);
	}

	private void updateSystemProperty() {
		this.username = System.getProperty("user.name");
		this.jTextField1.setText(username);
		this.jTextField1.setEditable(false);

	}

	private void updateLocalHostName() throws UnknownHostException {
		jTextField2.setText(InetAddress.getLocalHost().getHostName());
		jTextField2.setEditable(false);
	}

	private void updateOnlineOpponentsGame(String hostGame) {
		if (!instanceListModelOnlineGames.contains(hostGame)) {
			instanceListModelOnlineGames.addElement(hostGame);
		}
		gamingOpponents.setModel(instanceListModelOnlineGames);
		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        opponentsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gameList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        gamingOpponents = new javax.swing.JList<>();
        onlineGames = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        endButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select the opponent and the game", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        jPanel2.setToolTipText("");

        connectButton.setText("Connect");
        connectButton.setFocusPainted(false);
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        opponentsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                opponentsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(opponentsList);

        jLabel1.setText("Online Users");

        jLabel2.setText("Available Games");

        jLabel3.setText("Username:");

        jLabel4.setText("HostName:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        gameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                gameListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(gameList);

        gamingOpponents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                gamingOpponentsValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(gamingOpponents);

        onlineGames.setText("Active Games");

        playButton.setText("Play");

        endButton.setText("End Game");
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2))))
                .addGap(9, 9, 9))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(connectButton)
                        .addGap(18, 18, 18)
                        .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(endButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(onlineGames))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onlineGames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(endButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("Select the opponent and the game");
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
		opp = opponentsList.getSelectedValue();
		if (opp != null && gameList.getSelectedValue() != null) {

			this.gameController.setContinuousTarget(opp);

			gameController.
				establishConnection(opp, "::. Receive information .::\n"
									+ "A host " + opp + " wants to play "
									+ " with you.\n Game: " + gameList.
									getSelectedValue() + " Do you wish to play with him ?");

		} else {
			JOptionPane.showMessageDialog(this, "Impossible to connect");
		}
    }//GEN-LAST:event_connectButtonActionPerformed

    private void opponentsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_opponentsListValueChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_opponentsListValueChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
		//photo upload handler
		final JFileChooser fc = new JFileChooser();

		int returnVal = fc.showOpenDialog(fc);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			photoFile = fc.getSelectedFile();
			this.jLabel5.setIcon(iconImageFromFile(photoFile));

		}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void gameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_gameListValueChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_gameListValueChanged

    private void gamingOpponentsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_gamingOpponentsValueChanged
		// TODO add your handling code here:
    }//GEN-LAST:event_gamingOpponentsValueChanged

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
		if (gamingOpponents.getSelectedValue() != null) {

			int reply = JOptionPane.
				showConfirmDialog(this, "::. Disconnect from instance .::\n"
								  + "Are you sure you want to disconnect?");

			if (reply == JOptionPane.YES_OPTION) {

				this.gameController.stopConnection();
				instanceListModelOnlineGames.removeElement(gamingOpponents.
					getSelectedValue());
			} else if (reply == JOptionPane.NO_OPTION) {
				// nothing to do
			}
		} else {
			JOptionPane.showMessageDialog(this, "Please choose a game to end.");
		}
    }//GEN-LAST:event_endButtonActionPerformed

	/**
	 * Fill the list with the available games. Dummy classes.
	 */
	private void updateListOfGames() {
		instanceListModelGames.add(0, TIC_TAC_TOE);
		TicTacToe ticTacToe = new TicTacToe();

		instanceListModelGames.add(1, BATTLESHIPS);
		Battleships battleships = new Battleships();

		gameList.setModel(instanceListModelGames);
	}

	/**
	 * Upload image to user profile.
	 *
	 * @param photoFile
	 * @return
	 */
	private ImageIcon iconImageFromFile(File photoFile) {
		try {
			BufferedImage img = ImageIO.read(photoFile);
			return scaledImageIcon(img);
		} catch (IOException ex) {
			JOptionPane.
				showMessageDialog(this, "Error opening file!", "User Photo", JOptionPane.ERROR_MESSAGE);
			return null;
		}
	}

	/**
	 * Convert image do ImageIcon.
	 *
	 * @param theImage
	 * @return
	 */
	private ImageIcon scaledImageIcon(Image theImage) {
		return new ImageIcon(theImage.getScaledInstance(100, 100,
														Image.SCALE_SMOOTH));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JButton endButton;
    private javax.swing.JList<String> gameList;
    private javax.swing.JList<String> gamingOpponents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel onlineGames;
    private javax.swing.JList<String> opponentsList;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables

	@Override
	public void selectionChanged(SelectionEvent event) {
		//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
	}

	@Override
	public void update(Observable o, Object object) {
		if (object instanceof List) {
			List<String> addresses = (List<String>) object;
			updateInstanceList(addresses);
		}

		if (object instanceof String) {

			if (((String) object).compareTo("TRUE") == 0) {
				JOptionPane.
					showMessageDialog(this, "Success! Connection establish");
				updateOnlineOpponentsGame("Opponent: " + opp + " | Game: " + gameList.
					getSelectedValue());
				this.gameController.updateOpponentActiveGames(opp);
			} else if (((String) object).compareTo("FALSE") == 0) {
				JOptionPane.
					showMessageDialog(this, "Cant establish connection");

			} else if (((String) object).compareTo("update") == 0) {
				updateOnlineOpponentsGame(opp);
			}
		}
	}

	/**
	 * Update the list of "online" instances.
	 *
	 * @param addresses
	 */
	public void updateInstanceList(List<String> addresses) {
		for (String address : addresses) {
			if (!instanceListModel.contains(address)) {
				instanceListModel.addElement(address);

				manager.after(20).once(new Task() {
					public void fire() {
						instanceListModel.removeElement(address);
						opponentsList.setModel(instanceListModel);
					}
				});
			}
		}
	}
}
