@startuml doc-files/analysis.png

participant "User" as User
participant "System" as System

User->System : Selects a range of cells and chooses to sort them.
System->User: Asks for the column to sort, the type of value to sort, and either ascending or descending.
User->System: Inputs preferences and submits.
System->User: Shows the sorted columns.

@enduml
