/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.task.ui;

import csheets.domain.Contact;
import csheets.domain.Task;
import csheets.ext.task.TaskController;
import csheets.ext.task.TaskExtension;
import csheets.framework.persistence.repositories.DataIntegrityViolationException;
import csheets.notification.Notification;
import csheets.ui.ctrl.UIController;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class TaskFrame extends javax.swing.JPanel implements Observer {

	/**
	 * Creates new form TaskFrame
	 */
	private final TaskController controller;
	private Task task;
	private List<Contact> listContact = new ArrayList();

	public TaskFrame(UIController uiController) {
		this.setName(TaskExtension.NAME);
		this.controller = new TaskController(uiController);
		this.initComponents();
		Notification.taskInformer().addObserver(this);
		Notification.contactInformer().addObserver(this);
		this.update(null, null);
	}

	public void update(Observable o, Object arg) {
		if (arg instanceof Contact || arg == null) {
			this.jComboBoxContacts.removeAllItems();
			for (Contact c : controller.showContacts()) {
				jComboBoxContacts.addItem(c);
				this.listContact.add(c);
			}
		} else if (arg instanceof Task) {
			this.jPanelTasks.removeAll();
			((GridLayout) this.jPanelTasks.getLayout()).setRows(5);
			for (Task task : this.controller.
				allTasksContact(this.listContact.get(this.jComboBoxContacts.
						getSelectedIndex()))) {
				TaskPanelSingle panel = new TaskPanelSingle(this.controller, task);
				this.jPanelTasks.add(panel);
				GridLayout layout = (GridLayout) this.jPanelTasks.getLayout();
				layout.setRows(layout.getRows() + 1);
			}
			this.jPanelTasks.revalidate();
			this.jPanelTasks.repaint();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabelContact = new javax.swing.JLabel();
        jComboBoxContacts = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButtonAddTask = new javax.swing.JButton();
        jPanelTasks = new javax.swing.JPanel();

        jLabelContact.setText("Contact");

        jComboBoxContacts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxContactsItemStateChanged(evt);
            }
        });
        jComboBoxContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxContactsActionPerformed(evt);
            }
        });

        jButtonAddTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csheets/res/img/add_event.png"))); // NOI18N
        jButtonAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTaskActionPerformed(evt);
            }
        });

        jPanelTasks.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddTask))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddTask)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTasks, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxContactsActionPerformed
    }//GEN-LAST:event_jComboBoxContactsActionPerformed

    private void jButtonAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTaskActionPerformed
		TaskManager manager = new TaskManager(this.controller, null, this.listContact.
											  get(this.jComboBoxContacts.
												  getSelectedIndex()));
		int eventOption = JOptionPane.
			showConfirmDialog(null, manager, "Create/Edit Task", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
		if (eventOption == JOptionPane.OK_OPTION) {
			try {
				manager.createTask();
			} catch (DataIntegrityViolationException ex) {
				Logger.getLogger(TaskFrame.class.getName()).
					log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jButtonAddTaskActionPerformed

    private void jComboBoxContactsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxContactsItemStateChanged
		/*
		 if (!listContact.isEmpty()) {
		 this.jPanelTasks.removeAll();
		 ((GridLayout) this.jPanelTasks.getLayout()).setRows(5);
		 for (Task task : this.controller.
		 allTasksContact(this.listContact.get(this.jComboBoxContacts.
		 getSelectedIndex()))) {
		 TaskPanelSingle panel = new TaskPanelSingle(this.controller, task);
		 this.jPanelTasks.add(panel);
		 GridLayout layout = (GridLayout) this.jPanelTasks.getLayout();
		 layout.setRows(layout.getRows() + 1);
		 }
		 this.jPanelTasks.revalidate();
		 this.jPanelTasks.repaint();
		 }
		 */
    }//GEN-LAST:event_jComboBoxContactsItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTask;
    private javax.swing.JComboBox jComboBoxContacts;
    private javax.swing.JLabel jLabelContact;
    private javax.swing.JPanel jPanelTasks;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
