/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.comments.ui;

import csheets.core.Cell;
import csheets.ext.comments.Comment;
import csheets.ext.comments.CommentableCell;
import csheets.ext.comments.CommentableCellListener;
import csheets.ext.comments.CommentsExtension;
import csheets.ui.ctrl.SelectionEvent;
import csheets.ui.ctrl.SelectionListener;
import csheets.ui.ctrl.UIController;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Rafael
 */
public class CommentsPanel extends javax.swing.JPanel implements SelectionListener,
	CommentableCellListener {

	/**
	 * The commentable cell currently being displayed in the panel
	 */
	private CommentableCell cell;

	/**
	 * The selected commentable cell's list of comments
	 */
	private List<CommentPanel> listComments;

	/**
	 * The assertion controller
	 */
	private CommentController controller;

	private JPanel jPanel1;
	private JPanel jPanel2;
	private JTextField txtBox;
	private GridLayout layout = new GridLayout(5, 1);

	/**
	 * Creates new form CommentsPanel
	 *
	 * @param uiController the UIController
	 */
	public CommentsPanel(UIController uiController) {
		setName(CommentsExtension.NAME);
		initComponents();

		jPanel1 = new JPanel();
		jPanel2 = new JPanel(layout);
		txtBox = new JTextField();
		jPanel1.add(txtBox);
		add(jPanel1, BorderLayout.NORTH);
		add(jPanel2, BorderLayout.CENTER);

		// Creates controller
		controller = new CommentController(uiController);
		uiController.addSelectionListener(this);

		// Creates comment components
		CommentsPanel.ApplyAction applyAction = new CommentsPanel.ApplyAction();

		//comment.setPreferredSize(new Dimension(120, 240));		// width, height
		//comment.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));		// width, height
		txtBox.addFocusListener(applyAction);
		txtBox.setAlignmentX(Component.CENTER_ALIGNMENT);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	/**
	 * Updates the comments field
	 *
	 * @param event the selection event that was fired
	 */
	@Override
	public void selectionChanged(SelectionEvent event) {
		Cell selectedCell = event.getCell();
		if (selectedCell != null) {
			CommentableCell activeCell
				= (CommentableCell) selectedCell.
				getExtension(CommentsExtension.NAME);
			activeCell.addCommentableCellListener(this);

			commentChanged(activeCell);
		}

		// Stops listening to previous active cell
		if (event.getPreviousCell() != null) {
			((CommentableCell) event.getPreviousCell().
				getExtension(CommentsExtension.NAME))
				.removeCommentableCellListener(this);
		}
	}

	/**
	 * Updates the comment field when the comments of the active cell is
	 * changed.
	 *
	 * @param cell the cell whose comments changed
	 */
	@Override
	public void commentChanged(CommentableCell cell) {
		// Stores the cell for use when applying comments
		this.cell = cell;

		if (this.cell.hasComments()) {
			paintCommentPanels();
		}

	}

	private void paintCommentPanels() {
		jPanel2.removeAll();
		refreshUI();
		List<Comment> commentsList = controller.getCommentList(this.cell);
		for (Comment comment : commentsList) {
			CommentPanel cmtPanel = new CommentPanel(comment.userName(), comment.
													 text());
			System.out.println("ADDED Panel for comment from " + comment.
				userName());

			jPanel2.add(cmtPanel);
			cmtPanel.setVisible(true);
		}
		refreshUI();
	}

	private void refreshUI() {
		revalidate();
		repaint();
	}

	protected class ApplyAction implements FocusListener {

		@Override
		public void focusGained(FocusEvent e) {

		}

		@Override
		public void focusLost(FocusEvent e) {
			// TODO Auto-generated method stub
			if (cell != null) {
				String comment = txtBox.getText().trim();
				System.out.println("DEBUG: comment = " + comment);
				if (!comment.isEmpty() && !"".equalsIgnoreCase(comment)) {
					System.out.println("DEBUG: has comments... adComment()");
					controller.addComment(cell, txtBox.getText());
				}
			}
		}
	}
}
