/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.comments.ui;

import csheets.ext.comments.Comment;
import csheets.notification.Notification;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Carlos Mateus
 */
public class HistoryFrame extends javax.swing.JFrame implements Observer {

	private CommentController controller;
	private Comment comment;

	/**
	 * Creates new form NewJFrame
	 */
	public HistoryFrame(CommentController controller, Comment comment) {
		this.controller = controller;
		this.comment = comment;
		this.initComponents();
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		this.update(null, null);
		Notification.commentInformer().addObserver(this);
	}

	@Override
	public void update(Observable o, Object arg) {
		this.jPanelVersions.removeAll();
		((GridLayout) this.jPanelVersions.getLayout()).setRows(5);
		if (this.comment != null) {
			for (Comment comment : this.comment.commentHistory()) {
				HistoryPanelSingle panel = new HistoryPanelSingle(this.controller, comment);
				this.jPanelVersions.add(panel);
				GridLayout layout = (GridLayout) this.jPanelVersions.
					getLayout();
				layout.setRows(layout.getRows() + 1);
			}
		}
		this.jPanelVersions.revalidate();
		this.jPanelVersions.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanelVersions = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("Historico!");

        jPanelVersions.setLayout(new java.awt.GridLayout(5, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(0, 244, Short.MAX_VALUE))
                    .addComponent(jPanelVersions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelVersions, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelVersions;
    // End of variables declaration//GEN-END:variables
}
