@startuml doc-files/crm_contacts_with_tags_design_sd_3.png


User -> TagUI : select contact to add tag
TagUI -> TagController: getSelectedContact(contact)
TagController -> Persistence : repositoryFactory = repositories()
Persistence -> AppSettings : instance()
Persistence -> AppSettings : getRepositoryFactory()
create "<interface>\nRepositoryFactory"
AppSettings -> "<interface>\nRepositoryFactory" : create()
AppSettings --> Persistence : RepositoryFactory
Persistence --> TagController : RepositoryFactory
TagController -> "<interface>\nRepositoryFactory" : contactsRepository()
"<interface>\nRepositoryFactory" -> "<interface>\nContactRepository": getSelectedContact(contact)
TagController <-- "<interface>\nContactRepository": contact

@enduml
