package csheets.ext.tags.ui;

import csheets.domain.Contact;
import csheets.ext.contacts.ContactsExtension;
import csheets.ext.tags.TagController;
import csheets.notification.Notification;
import csheets.ui.ctrl.UIController;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Marcelo Barroso 1131399
 */
public class ContactPanel extends javax.swing.JPanel implements Observer {

	private TagController controller;
	private Contact user;

	/**
	 * Creates new form ContactsPanel
	 *
	 * @param uiController The user interface controller.
	 */
	public ContactPanel(UIController uiController) {
		this.setName(ContactsExtension.NAME);
		this.controller = new TagController(uiController, this);
		this.user = this.controller.systemUser();
		this.initComponents();
		this.update(null, null);
		Notification.contactInformer().addObserver(this);
	}

	@Override
	public void update(Observable o, Object arg) {
		this.user = this.controller.systemUser();
		this.jPanelContacts.removeAll();
		((GridLayout) this.jPanelContacts.getLayout()).setRows(5);
		for (Contact contact : this.controller.allContactsTag()) {
			ContactPanelSingle panel = new ContactPanelSingle(this.controller, contact);
			this.jPanelContacts.add(panel);
			GridLayout layout = (GridLayout) this.jPanelContacts.
				getLayout();
			layout.setRows(layout.getRows() + 1);
		}
		this.jPanelContacts.revalidate();
		this.jPanelContacts.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelContacts = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelContacts.setLayout(new java.awt.GridLayout(5, 1));
        jScrollPane1.setViewportView(jPanelContacts);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
		controller.setText(this.jTextField1.getText());
		this.update(null, null);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContacts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
