@startuml doc-files/forms_editor_design.png

actor User
participant "<<analysis>>\nFormEditorUI" as FormEditorUI



User->FormEditorUI: form().
loop
FormEditorUI->FormFrame: new()
alt add
FormFrame->AskContent: add()
AskContent->SingleLine:add(name, description)
SingleLine->FormFrame: added()
FormFrame->FormFrame: refresh()
end
alt remove
FormFrame->SingleLine: remove()
SingleLine->FormFrame: removed()
FormFrame->FormFrame: refresh()
end

end

@enduml