@startuml doc-files/chat_app_analysis.png

actor User
participant "<<analysis>>\nFormEditorUI" as FormEditorUI



User->FormEditorUI: form().
loop
FormEditorUI->FormFrame: new()
alt add
User->FormFrame: add(name, description)
FormFrame->FormController: add()
FormController->FormPanelSingle: new()
FormPanelSingle->FormFrame:added()
FormFrame->FormFrame: refresh()
end
alt remove
User->FormFrame: remove()
FormFrame->FormController: remove()
FormController->FormPanelSingle: remove()
FormPanelSingle->FormFrame:removed()
FormFrame->FormFrame: refresh()
end

end

@enduml