/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.reminder.ui;

import csheets.domain.Event;
import csheets.domain.Reminder;
import csheets.ext.events.EventsController;
import csheets.ext.reminder.RemindersControllers;

/**
 *
 * @author Gabriel
 */
public class ReminderSinglePanel extends javax.swing.JPanel {
    private final RemindersControllers controller;
    private final Reminder reminder;
    
    /**
     * Creates new form ReminderSinglePanel
     */
    public ReminderSinglePanel(RemindersControllers control, Reminder remind) {
        this.controller=control;
        this.reminder=remind;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
