/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csheets.ext.conditionalFormatting.ui;

import csheets.core.Cell;
import csheets.core.IllegalValueTypeException;
import csheets.core.Spreadsheet;
import csheets.core.Value;
import csheets.core.Workbook;
import csheets.core.formula.compiler.FormulaCompilationException;
import csheets.ext.conditionalFormatting.ConditionalFormattingExtension;
import csheets.ext.style.ui.BackgroundAction;
import csheets.ext.style.ui.BorderAction;
import csheets.ext.style.ui.FontAction;
import csheets.ext.style.ui.ForegroundAction;
import csheets.ext.style.ui.FormatAction;
import csheets.ui.ctrl.UIController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diogo Leite
 */
public class ConditionalFormattingUI extends JPanel {

	private final UIController uiController;
	private final ConditionalFormattingController conditionalFormattingController;
	/**
	 * Cell selected
	 */
	private Cell cell;

	/**
	 * Creates new form ConditionalFormattingUI
	 *
	 * @param uiController UIController
	 */
	public ConditionalFormattingUI(UIController uiController) {

		setName(ConditionalFormattingExtension.NAME);
		initComponents();
		this.uiController = uiController;
		this.conditionalFormattingController = new ConditionalFormattingController();

		Workbook work = new Workbook(1);
		Spreadsheet s = work.getSpreadsheet(0);
		cell = s.getCell(0, 0);

		this.toolBarTrueFont.add(new FontAction(uiController));
		this.toolBarFalseFont.add(new FontAction(uiController));
		this.toolBarTrueForeground.add(new ForegroundAction(uiController));
		this.toolBarFalseForeground.add(new ForegroundAction(uiController));
		this.toolBarTrueBackground.add(new BackgroundAction(uiController));
		this.toolBarFalseBackground.add(new BackgroundAction(uiController));
		this.toolBarTrueBorder.add(new BorderAction(uiController));
		this.toolBarFalseBorder.add(new BorderAction(uiController));
		this.toolBarTrueFormat.add(new FormatAction(uiController));
		this.toolBarFalseFormat.add(new FormatAction(uiController));

		this.setVisible(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFont = new javax.swing.JLabel();
        labelForeground = new javax.swing.JLabel();
        labelBackground = new javax.swing.JLabel();
        labelBorder = new javax.swing.JLabel();
        labelAlign = new javax.swing.JLabel();
        labelFormat = new javax.swing.JLabel();
        trueLabel = new javax.swing.JLabel();
        falseLabel = new javax.swing.JLabel();
        labelExpression = new javax.swing.JLabel();
        textFieldFormula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnTest = new javax.swing.JButton();
        toolBarTrueFont = new javax.swing.JToolBar();
        toolBarFalseFont = new javax.swing.JToolBar();
        toolBarTrueForeground = new javax.swing.JToolBar();
        toolBarFalseForeground = new javax.swing.JToolBar();
        toolBarTrueBackground = new javax.swing.JToolBar();
        toolBarFalseBackground = new javax.swing.JToolBar();
        toolBarTrueBorder = new javax.swing.JToolBar();
        toolBarFalseBorder = new javax.swing.JToolBar();
        toolBarTrueAlign = new javax.swing.JToolBar();
        toolBarFalseAlign = new javax.swing.JToolBar();
        toolBarTrueFormat = new javax.swing.JToolBar();
        toolBarFalseFormat = new javax.swing.JToolBar();
        btnApply = new javax.swing.JButton();

        setAlignmentY(0.1F);

        labelFont.setText("Font");

        labelForeground.setText("Foreground");

        labelBackground.setText("Background");

        labelBorder.setText("Border");

        labelAlign.setText("Align");

        labelFormat.setText("Format");

        trueLabel.setText("True");

        falseLabel.setText("False");

        labelExpression.setText("Expression");

        btnTest.setText("Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        toolBarTrueFont.setRollover(true);

        toolBarFalseFont.setRollover(true);

        toolBarTrueForeground.setRollover(true);

        toolBarFalseForeground.setRollover(true);

        toolBarTrueBackground.setRollover(true);

        toolBarFalseBackground.setRollover(true);

        toolBarTrueBorder.setRollover(true);

        toolBarFalseBorder.setRollover(true);

        toolBarTrueAlign.setRollover(true);

        toolBarFalseAlign.setRollover(true);

        toolBarTrueFormat.setRollover(true);

        toolBarFalseFormat.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelExpression)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldFormula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(trueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(falseLabel)
                .addGap(38, 38, 38))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFont)
                            .addComponent(labelForeground))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueFont, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                                .addComponent(toolBarFalseFont, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueForeground, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toolBarFalseForeground, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBackground)
                            .addComponent(labelBorder)
                            .addComponent(labelAlign)
                            .addComponent(labelFormat))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueAlign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toolBarFalseAlign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toolBarFalseBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toolBarTrueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toolBarFalseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toolBarFalseFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExpression)
                    .addComponent(textFieldFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTest))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trueLabel)
                    .addComponent(falseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(toolBarFalseFont, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toolBarFalseForeground, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFont)
                            .addComponent(toolBarTrueFont, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelForeground)
                            .addComponent(toolBarTrueForeground, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBackground)
                    .addComponent(toolBarTrueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolBarFalseBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBorder)
                    .addComponent(toolBarTrueBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolBarFalseBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolBarTrueAlign, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolBarFalseAlign, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormat)
                    .addComponent(toolBarTrueFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolBarFalseFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnApply)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApply)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
		try {
			conditionalFormattingController.apply(cell);
		} catch (FormulaCompilationException ex) {
			Logger.getLogger(ConditionalFormattingUI.class.getName()).
				log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
		if (!textFieldFormula.getText().isEmpty()) {

			try {
				// TODO add your handling code here:
				cell.setContent(textFieldFormula.getText());
			} catch (FormulaCompilationException ex) {
				defaultLabelColor();
			}

			try {

				if (cell.getValue().
					isOfType(Value.Type.BOOLEAN)) {
					if (cell.getValue().toBoolean()) {
						trueLabel.setForeground(Color.red);
						falseLabel.setForeground(Color.black);
					} else {
						trueLabel.setForeground(Color.black);
						falseLabel.setForeground(Color.red);
					}
				} else {
					defaultLabelColor();
				}

			} catch (IllegalValueTypeException ex) {
				Logger.getLogger(ConditionalFormattingUI.class.getName()).
					log(Level.SEVERE, null, ex);
			}
		} else {
			defaultLabelColor();
		}
    }//GEN-LAST:event_btnTestActionPerformed

	private void defaultLabelColor() {
		trueLabel.setForeground(new JLabel().getForeground());
		falseLabel.setForeground(new JLabel().getForeground());
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel falseLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAlign;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelBorder;
    private javax.swing.JLabel labelExpression;
    private javax.swing.JLabel labelFont;
    private javax.swing.JLabel labelForeground;
    private javax.swing.JLabel labelFormat;
    private javax.swing.JTextField textFieldFormula;
    private javax.swing.JToolBar toolBarFalseAlign;
    private javax.swing.JToolBar toolBarFalseBackground;
    private javax.swing.JToolBar toolBarFalseBorder;
    private javax.swing.JToolBar toolBarFalseFont;
    private javax.swing.JToolBar toolBarFalseForeground;
    private javax.swing.JToolBar toolBarFalseFormat;
    private javax.swing.JToolBar toolBarTrueAlign;
    private javax.swing.JToolBar toolBarTrueBackground;
    private javax.swing.JToolBar toolBarTrueBorder;
    private javax.swing.JToolBar toolBarTrueFont;
    private javax.swing.JToolBar toolBarTrueForeground;
    private javax.swing.JToolBar toolBarTrueFormat;
    private javax.swing.JLabel trueLabel;
    // End of variables declaration//GEN-END:variables

}
